<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Доступ запрещен</title>
    <link rel="stylesheet" href="../css/registrationFailed.css">

</head>
<body>
<div class="container">
    <h1>403</h1>
    <p>Данные были некорректно введены.</p>
</div>
<div class="space">
    <button type="submit" class="register-button">
        <a class="text-color" href="/login">Вернуться назад</a>
    </button>
</div>
</body>
</html>
